version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: php_app
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - db
    command: bash -c "docker-php-ext-install pdo pdo_mysql && php-fpm"

  nginx:
    image: nginx:1.27
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

volumes:
  db_data:
